name: memolidays
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3 #Cupertino Icons font
  google_sign_in: ^4.5.1 #Package for connection with Google account
  firebase_core: ^0.5.0 #Enable Firebase connexion
  firebase_auth: ^0.18.1 #Handle Google connexion
  http: ^0.12.1 #For http requests
  get: ^3.17.1 #Handle routes
  flushbar: ^1.10.4 #Snackbar for errors displays
  flutter_form_builder: ^3.13.6 #For form creation 
  material_tag_editor: ^0.0.4 #Material design for tags
  data_connection_checker: ^0.3.4 #Check connectivity
  states_rebuilder: 3.0.0 #States manager
  hive: ^1.4.4+1 #Store local data
  hive_flutter: ^0.3.1 #Store local data for Flutter
  motion_tab_bar: ^0.1.5
  # motion_tab_bar: #Customize BottomTabBar
  #   git: #Repo for custom motion tab bar
  #     url : https://github.com/Antonin06/Motion-Tab-Bar.git
  flutter_staggered_grid_view: ^0.3.2 #For photos staggered grid
  photo_view: ^0.10.2 #Enable zoom rotation and drag for images
  font_awesome_flutter: ^8.10.0 #Font Awesome icon pack
  hexcolor: ^1.0.6 #For hexadecimal colors
  flutter_svg: ^0.19.1 #Enable SVG files
  url_launcher: ^5.7.5 #Android and iOS url launching
  image_picker: ^0.6.7+12 #Pick images in device & take photos with camera
  multi_image_picker: ^4.7.14 #Pick multiple images
  cached_network_image: ^2.3.3 #Load and cache network images
  intl: ^0.16.1 #Localization & date formatting
  flutter_map: ^0.10.1+1 #Interactive map
  geolocator: ^6.1.1 #Location and distances
  geocoding: ^1.0.5 #Translate coordinates to places
  latlng: ^0.0.2 #Geodesy and geographical calculations
  mapbox_gl: ^0.9.0 #Customize maps
  lat_lon_grid_plugin: ^0.1.3 #Latitude/longitude grid 
  user_location: #Handle and plot current user location
    git:
      url: https://github.com/igaurab/user_location_plugin.git
  progress_state_button: ^1.0.1 #Customizable progress button
  flutter_dotenv: ^3.1.0
  mapbox_search_flutter: ^1.0.6+1 #Location search

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.1 #Store local data
  build_runner: ^1.10.3 #Store local data (hive)

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icon.png
    - assets/images/google.svg
    - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
