name: memolidays
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3 #Cupertino Icons font
  google_sign_in: ^4.5.1 #Package for connection with Google account
  firebase_core: ^0.5.0 #Handle Firebase connexion
  firebase_auth: ^0.18.1 #Handle Firebase connexions and their parameters
  http: ^0.12.1 #Load API
  get: ^3.12.1 #Handle routes
  flushbar: ^1.10.4 #Snackbar for errors displays
  flutter_form_builder: ^3.13.6
  material_tag_editor: ^0.0.4
  # flutter_material_pickers: ^1.8.0
  data_connection_checker: ^0.3.4 #Check connectivity
  states_rebuilder: 3.0.0 #States manager
  hive: ^1.4.4+1 #Store local data
  hive_flutter: ^0.3.1 #Store local data
  motion_tab_bar: #Permet la customisation de la BottomTabBar
    git: 
      url : https://github.com/Antonin06/Motion-Tab-Bar.git
  flutter_staggered_grid_view: ^0.3.2 #Permet la masonry grid
  transparent_image : ^1.0.0 
  photo_view: ^0.10.2 
  font_awesome_flutter: ^8.10.0
  hexcolor: ^1.0.6 #Permet de convertir les Colors.### en hexadecimal
  flutter_svg: ^0.19.1 #Permet l'utilisation de SVG
  url_launcher: ^5.7.5
  image_picker: ^0.6.7+12
  multi_image_picker: ^4.7.14
  cached_network_image: ^2.3.3
  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.1 #Store local data
  build_runner: ^1.10.3 #Store local data (hive)

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icon.png
    - assets/images/google.svg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
